### ISSUE TITLE
Crash "all cards" option

### ISSUE THREAD

**Issue by hataian2003** [AlexsanderRST/EDOPro-HD-Pics-Downloader#10]
![image](https://user-images.githubusercontent.com/23236908/140398779-cd99c7bf-22ec-4990-9301-fa9643a4da9c.png)
Hi, i just download the .exe file and ran the all cards in the program but is crashed at only about 12/11610 .

**Comment by AlexsanderRST** [comment]
Hey, thanks for report. I need to update the .exe file to may solve this issue, but it gonna take a while.

> FileNotFoundError and urllib.error.URLError unhandled by download function

**Comment by AlexsanderRST** [comment]
New update (2.1.5). Check out if the error still remains.

**Comment by hataian2003** [comment]
ok

**Comment by hataian2003** [comment]
Is there something wrong because the windows defender started seeing the program as a trojan/virus or something.

**Comment by AlexsanderRST** [comment]
This is problem with the library that converts .py file to exe (auto-py-to-exe), but it's a false positive:

[https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg](url)

I sent the file to Avast and VirusTotal to analysis. It may take a while to get validated as false positive.
