### ISSUE TITLE
Card images should be accessed via the API instead of the web site

### ISSUE THREAD

**Issue by larikk** [AlexsanderRST/EDOPro-HD-Pics-Downloader#12]
See https://db.ygoprodeck.com/api-guide/#card-images

The site owner does not like it when the images are scraped from the web site. But using the API is easier in my opinion and I'm pretty sure that the images are the same:

Site: https://ygoprodeck.com/pics/40640057.jpg
API: https://storage.googleapis.com/ygoprodeck.com/pics/40640057.jpg

You can get a list of all cards (including images) by requesting https://db.ygoprodeck.com/api/v7/cardinfo.php . With that list you should be able to determine which images need to be downloaded by checking for their existence and dimensions.

**Comment by AlexsanderRST** [comment]
Hello. I already use the API:

```
if mode == 'allfields':
                dwnld_info = {'database_url': 'https://storage.googleapis.com/ygoprodeck.com/pics_artgame/',
                              'pics_folder': 'pics/field/',
                              'pics_extension': '.png'}
            else:
                dwnld_info = {'database_url': 'https://storage.googleapis.com/ygoprodeck.com/pics/',
                              'pics_folder': 'pics/',
                              'pics_extension': '.jpg'}
``` 

I make some discreet scrap to get the list of new cards, but it isn’t related to the end user. It is actually in another file called _HD Pics Tools.py_: 

```url = f'https://db.ygoprodeck.com/search/?{flags}&offset={offset}&view=List'```

The list of all cards is updated from here.

**Comment by larikk** [comment]
Alright, nvm me then. I only skimmed over your code because I was curious about where you get HQ images from and assumed that you scrape the web site. Sorry for that.
