### ISSUE TITLE
"Fatal error detected" again with latest version

### ISSUE THREAD

**Issue by CaptainMetal92** [AlexsanderRST/EDOPro-HD-Pics-Downloader#16]
After updating to the new .exe version I again get the
"Fatal error detected

Failed to execute script hd_cards_dwnlder"
issue when trying to launch the program. Again neither a re-download nor running as admin changed anything.

**Comment by AlexsanderRST** [comment]
If the program is crashing at launch, probably is the version check. I will release a new update this weekend, it's not guaranteed that will solve this issue but with the improved log I can catch some bugs easily.

**Comment by AlexsanderRST** [comment]
New update. Into the folder you execute the program, there's a file called **_HD Pics Downloader log.txt_**. Just drop the text here.

**Comment by CaptainMetal92** [comment]
Thanks works perfectly again
