### ISSUE TITLE
Token cards are not downloaded

### ISSUE THREAD

**Issue by 007FFF** [AlexsanderRST/EDOPro-HD-Pics-Downloader#23]
For example, Primal Being Token (https://storage.googleapis.com/ygoprodeck.com/pics/27204312.jpg).

**Comment by AlexsanderRST** [comment]
It's because they are not into allcards.ydk. I will include them when I update the file.

**Comment by 007FFF** [comment]
> It's because they are not into allcards.ydk. I will include them when I update the file.

Thank you. I notice you can't search for them on the ygoprodeck site directly. What's up with that?

**Comment by AlexsanderRST** [comment]
I updated the 'All cards' to include the majority of tokens. The 'New cards' also downloads them. I also included a _alltokens.ydk_ to download them separately with Text Input. If you find any missing ids or other bugs, open another issue.
