### ISSUE TITLE
Crash "all fields" option

### ISSUE THREAD

**Issue by Lahrenheit** [AlexsanderRST/EDOPro-HD-Pics-Downloader#9]
![image](https://user-images.githubusercontent.com/67435388/139152113-53afbd5c-220a-44ad-b2c8-97d065061dfc.png)

Hi, it appear when I use the "all fields" option, like in 70/261

P.S: I use the .exe version

**Comment by AlexsanderRST** [comment]
Did it work or the error still remains?

**Comment by AlexsanderRST** [comment]
New update (2.1.5). Check out if the error still remains.

**Comment by Lahrenheit** [comment]
hi, it freezes again but no error, btw when I start the app again works, and  after a few minutes freezes again (not responding) and I have to close and open or restore program and works

**Comment by AlexsanderRST** [comment]
No error window popping-up means the previous bug was probably solved. Here more questions:
1. Is it freezing only when you use **all fields** function? 
2. Is your internet stable? If you cut the connection while downloading, the program will freezes and not respond. I will solve or workaround these connection problems in the next update

**Comment by Lahrenheit** [comment]
1. Yes, only tested with "all fields" option til now
2. Yes, I changed of isp

**Comment by AlexsanderRST** [comment]
New update. Into the folder you execute the program, there's a file called HD Pics Downloader log.txt. Just drop the text here.

**Comment by Lahrenheit** [comment]
[HD Pics Downloader log.txt](https://github.com/AlexsanderRST/EDOPro-HD-Pics-Downloader/files/7714995/HD.Pics.Downloader.log.txt)
Hi, here the logfile with the "all cards" option, only ~9000 files downloaded over ~12000 idk why
with "all fields" 222 files only downloaded too (not all files downloaded but the program show yes)

**Comment by AlexsanderRST** [comment]
Yes, the program counts as downloaded even it's not. But the majority of not downloaded pics is related to temporary cards ids. Now, the program should download ~11600 cards pics not 9000. Checking your log, I noticed a missing 'Download completed' line at the end before 'Program exited' and that is not supposed to happen. I'll open a new issue to this.
